name: Bug
description: Create a report to help us improve
labels: ["Bug"]
projects: ["dreamscore-oss/2"]
body:
  - type: markdown
    attributes:
      value: |
        ## Please fill in this bug report template to help us understand the issue.
  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: "Ex: When I tried to ..."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Ex: It should ..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (logs, screenshots, etc.).
