name: Risk
description: Identify and manage risks
labels: ["Risk"]
projects: ["dreamscore-oss/10"]
body:
  - type: markdown
    attributes:
      value: |
        ## Please provide details about the identified risk.
  - type: input
    id: risk-summary
    attributes:
      label: Risk Summary
      description: A brief summary of the risk identified.
      placeholder: "Ex: Potential for data leakage due to ..."
    validations:
      required: true
  - type: textarea
    id: risk-details
    attributes:
      label: Detailed Description
      description: A detailed description of the risk, including potential impact.
      placeholder: "Provide a detailed account of the identified risk, including possible consequences."
    validations:
      required: true
  - type: textarea
    id: mitigation-steps
    attributes:
      label: Mitigation Steps
      description: Proposed steps or measures to mitigate the risk.
      placeholder: "Outline any steps or actions that can be taken to mitigate the risk."
