spring:
  docker:
    compose:
      file: backend/compose.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/dreamscore
    username: postgres
    password: secret

petclinic.host.uri: http://localhost:8081
