spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.SpringJtaPlatform
    hibernate:
      ddl-auto: validate

  mustache:
    check-template-location: false

  liquibase:
    enabled: true

okta:
  oauth2:
    issuer: https://dreamscore.eu.auth0.com/
    audience: https://dreamscore/api
