#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'package-lock.json'; then
  echo ""
  echo "+----------------------------------------------------------------------------------------+"
  echo "| 📦 package-lock.json changed. Run 'npm install' to bring your dependencies up to date. |"
  echo "+----------------------------------------------------------------------------------------+"
  echo ""
fi

if changed 'env.example'; then
  echo ""
  echo "+------------------------------------------------------------------------------------------------+"
  echo "| ⚙️ env.example changed. Update your local .env to have all configurations up to date.  |"
  echo "+------------------------------------------------------------------------------------------------+"
  echo ""
fi